# servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nim-metrics
spec:
  selector:
    matchLabels:
      app: nim-inference
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
